### ISSUE TITLE
Accept regex quantifier

### ISSUE THREAD

**Issue by juanlatorre** [CaioQuirinoMedeiros/react-native-mask-input#1]
Hi, currently this kind of regex are not working at all.

`\d{1,3}`

**Comment by CaioQuirinoMedeiros** [comment]
Hi @juanlatorre, I'll take a look at this as soon as I can

**Comment by CaioQuirinoMedeiros** [comment]
@juanlatorre the validation is done for each character against a item on the mask array, so the regex `/\d{1,3}/` will actually behave the same as `/\d/`. If you want to allow three digits in sequence you should use `[/\d/, /\d/, /\d/]`.

If you need some dinamically rule, use a function to do your logic, like that:
```javascript
const myMask = (value: string) => {
  if (something) {
    return [/\d/]
  } else {
    return [/\d/, /\d/, /\d/]
  }
}
```

**Comment by juanlatorre** [comment]
Thanks for the quick validation, I will  implement a custom mask function then !
