### ISSUE TITLE
Currency format for trailing zeros?

### ISSUE THREAD

**Issue by zaura-payments** [CaioQuirinoMedeiros/react-native-mask-input#12]
Is it possible to add trailing zeros for a currency such as GBP?

If I use this mask: 

const mask = createNumberMask({
    prefix: ["£", " "],
    delimiter: ",",
    separator: ".",
    precision: 2,
  });
  
 With a value of £12 I want it to be displayed as £12.00
 
 How do I go about changing the mask or creating my own to do this?

**Comment by CaioQuirinoMedeiros** [comment]
@zaura-payments try this: https://github.com/CaioQuirinoMedeiros/react-native-currency-input

**Comment by CaioQuirinoMedeiros** [comment]
> > @zaura-payments try this: https://github.com/CaioQuirinoMedeiros/react-native-currency-input
> 
> This is great thanks! Is there any way I can shift the blinking indicator over to the left more? Even if I have to change the code directly?

It's not possible with that component
