### ISSUE TITLE
Warning: State updates from the useState() and useReducer() Hooks don't support the second callback argument...

### ISSUE THREAD

**Issue by MarianaOlimpia** [CaioQuirinoMedeiros/react-native-mask-input#13]
Hi. I'm having this warning when i use the component. I'm using it with the example from the documentation:
```
<MaskInput
      value={creditCard}
      onChangeText={setCreditCard}
      mask={Masks.CREDIT_CARD}
    />
```

![Captura de pantalla 2021-11-23 203800](https://user-images.githubusercontent.com/60668720/143161792-c3b786ea-f0d7-4fc0-a49c-ae8ac4312d54.png)

**Comment by CaioQuirinoMedeiros** [comment]
@MarianaOlimpia I'm pretty sure it's not related to the MaskInput component. Anyway, feel free to share a reproducible code example
