### ISSUE TITLE
how to mask iban number

### ISSUE THREAD

**Issue by ihsanktmr** [CaioQuirinoMedeiros/react-native-mask-input#14]
I can't enter strings with this mask -> 
```
export const IBANMask = [
  /\d/,
  /\d/,
  ' ',
  /\d/,
  /\d/,
  /\d/,
  /\d/,
  ' ',
  /\d/,
  /\d/,
  /\d/,
  /\d/,
  ' ',
  /\d/,
  /\d/,
  /\d/,
  /\d/,
  ' ',
  /\d/,
  /\d/,
  /\d/,
  /\d/,
  ' ',
  /\d/,
  /\d/,
  /\d/,
  /\d/,
  ' ',
  /\d/,
  /\d/,
];
```

I am trying to mask iban number for example -> GB29 NWBK 6016 1331 9268 19
Can you help me ? thanks

**Comment by arochedy** [comment]
Did you thind how to do it ??

**Comment by CaioQuirinoMedeiros** [comment]
@arochedy , read the [documentation](https://github.com/CaioQuirinoMedeiros/react-native-mask-input#mask), understand how the mask works and you should be able to build what you want...

On @ihsanktmr code he used `/\d/` for all inputs, but `/\d/` will match only numbers.

I do not know IBAN numbers, but you can try something like this:

```javascript
const ibanMask = [
  /[a-zA-Z]/,
  /[a-zA-Z]/,
  /\d/,
  /\d/,
  ' ',
  /\w/,
  /\w/,
  /\w/,
  /\w/,
  ' ',
  /\d/,
  /\d/,
  /\d/,
  /\d/,
  ' ',
  /\d/,
  /\d/,
  /\d/,
  /\d/,
  ' ',
  /\d/,
  /\d/,
  /\d/,
  /\d/,
  ' ',
  /\d/,
  /\d/,
  /\d/,
  /\d/,
];
```
