### ISSUE TITLE
Focus on an input

### ISSUE THREAD

**Issue by dlaynes-gl** [CaioQuirinoMedeiros/react-native-mask-input#17]
Hi. I'd like to use ref.focus() on the inner TextInput element. Is it possible? Thank you

**Comment by CaioQuirinoMedeiros** [comment]
Yes, just like a normal TextInput

**Comment by dlaynes-gl** [comment]
I'll try again soon with a typescript reference annotation with TextInput and not MaskInput and will post the results.

**Comment by dlaynes-gl** [comment]
This works properly in Typescript (forwardRef, useImperativeHandle). Thanks

const inputRef = createRef<TextInput>()
