### ISSUE TITLE
Masks that end with a string do not automatically fill the last character

### ISSUE THREAD

**Issue by mmfire118** [CaioQuirinoMedeiros/react-native-mask-input#21]
Using this mask for example:

`const MASK = [/\d/, /\d/, ".", /\d/, "%"]`

with an input of '221' outputs '22.1' NOT '22.1%'

The last character is only added after you input an additional character.

**Comment by CaioQuirinoMedeiros** [comment]
@mmfire118 it's not possible. See if this lib fits your case, it has `suffix` prop: https://github.com/CaioQuirinoMedeiros/react-native-currency-input
