### ISSUE TITLE
How to remove leading zeroes

### ISSUE THREAD

**Issue by KrisLau** [CaioQuirinoMedeiros/react-native-mask-input#27]
Exactly as the title: How do I remove the leading zeroes from a currency input using a `createNumberMask` as its mask?

**Comment by CaioQuirinoMedeiros** [comment]
@KrisLau if you want a currency input I recommend this one: https://github.com/CaioQuirinoMedeiros/react-native-currency-input

**Comment by KrisLau** [comment]
@CaioQuirinoMedeiros Does that remove leading zeroes?

**Comment by KrisLau** [comment]
also would I be able to get help on one of my masks? I'm trying to mask a number (in ms) to seconds

**Comment by CaioQuirinoMedeiros** [comment]
@KrisLau I don't get what you want... the documentation of both libraries are pretty clear, you should only come here if you face a problem

**Comment by KrisLau** [comment]
Sorry I'll explain in more detail! So the issue I was having in the original post has been resolved by moving to the https://github.com/CaioQuirinoMedeiros/react-native-currency-input package. 

The second issue I'm having is I have an input where users enter the number of milliseconds and I wanted the milliseconds to be formatted to seconds and milliseconds. like this ss:mm. I thought using `[/\/d/, /\/d/, ':', /\/d/, /\/d/]` would work but it was not even updating the value correctly

**Comment by CaioQuirinoMedeiros** [comment]
try `[/\d/, /\d/, ':', /\d/, /\d/]`

**Comment by KrisLau** [comment]
> try `[/\d/, /\d/, ':', /\d/, /\d/]`

@CaioQuirinoMedeiros Isn't that the same regex expression as what I had already tried unless I'm missing something? I thought that would work as well but it was not working for me. Here is my code in case that might help:
```
<MaskInput
    value={introStartTimeText}
    onChangeText={masked => {
      setIntroStartTimeText(masked);
    }}
    mask={[/\/d/, /\/d/, ':', /\/d/, /\/d/]}
    style={{
      height: 30,
      fontSize: 18,
      borderBottomWidth: 1,
      paddingHorizontal: 10,
      color: Colors.PRIMARY,
      borderColor: Colors.PRIMARY,
    }}
  /><MaskInput
    value={introStartTimeText}
    onChangeText={masked => {
      setIntroStartTimeText(masked);
    }}
    mask={[/\/d/, /\/d/, ':', /\/d/, /\/d/]}
    style={{
      height: 30,
      fontSize: 18,
      borderBottomWidth: 1,
      paddingHorizontal: 10,
      color: Colors.PRIMARY,
      borderColor: Colors.PRIMARY,
    }}
  />
```
