### ISSUE TITLE
Masked input with obfuscation delete's the last character always.

### ISSUE THREAD

**Issue by sahilbalodi** [CaioQuirinoMedeiros/react-native-mask-input#3]
A masked input with obfuscation deletes the last character if the user updates the cursor and tries to delete a character.

mask example : [[/\d/], [/\d/], [/\d/]].

if the user moves the cursor to position 2 and deletes a character it always deletes the last character.

text input : ```**|*```
deletes the last character instead of 2nd character.

**Comment by CaioQuirinoMedeiros** [comment]
Hi @sahilbalodi. I've been trying a lot to fix it but I couldn't find better solution than just use `selection` to force the cursor at the end of the value, thus preventing this scenario (only when there's obfuscation though)

I just release that fix on v1.0.3
