### ISSUE TITLE
Incorrect value for USA_PHONE mask

### ISSUE THREAD

**Issue by SikoraKam** [CaioQuirinoMedeiros/react-native-mask-input#30]
Mask USA_PHONE doesn't allow to write '1' as first digit. Only '(' appears

**Comment by CaioQuirinoMedeiros** [comment]
@SikoraKam take a look at the USA_PHONE Mask: https://github.com/CaioQuirinoMedeiros/react-native-mask-input/blob/abe14520a89ab1ec53671e4e8bb08dd0ab27a034/src/Masks.ts#L56-L71

these `Masks` are only common use cases and also serve as references, if none of them suits your use case, just write your own mask!
