### ISSUE TITLE
Feature request: put masking character in advance

### ISSUE THREAD

**Issue by lclarkg18** [CaioQuirinoMedeiros/react-native-mask-input#32]
First of all, love the library, and so happy to find one that works and is actually maintained.

From a UX perspective, I would prefer the slash in the case of dates to be set before the 3 characters are typed, so when a user types "01" it masks to "01/" instead of waiting for them to type the third number and then retroactively placing the slash. This may not be necessary for some use cases and I know I am being picky but an incredible feature would be to allow devs to configure this with a prop.

Thanks!

**Comment by CaioQuirinoMedeiros** [comment]
Thanks, @lclarkg18, I will study the viability of such feature

**Comment by CaioQuirinoMedeiros** [comment]
Added new prop `maskAutoComplete` on v1.2.3
