### ISSUE TITLE
If next symbol is defined prefill it before user entering the next input character

### ISSUE THREAD

**Issue by FDiskas** [CaioQuirinoMedeiros/react-native-mask-input#34]
It's hard to explain. Currently, when entering masked input characters all separators are inserted after user input.

wanted
![Untitled](https://user-images.githubusercontent.com/468006/221910813-2f97e05d-8afb-4a1e-b17a-e4091ac5d7a7.gif)

default
<img src="https://media.giphy.com/media/6CUiN9vx6RjbZUBd2p/giphy.gif" />

**Comment by CaioQuirinoMedeiros** [comment]
Use the prop `maskAutoComplete` from the latest version 1.2.3
