### ISSUE TITLE
Is it possible to either apply a mask or apply none?

### ISSUE THREAD

**Issue by seyadeodin** [CaioQuirinoMedeiros/react-native-mask-input#37]
I have a field that accept either an e-mail or a phone number, and I would like to know how to not apply a mask when the field is detected as an e-mail. Any falsy value I return receives a type error, since the field only accepts arrays. Is there at least a way of apply a mask that apply no mask?. This is more or less what I was trying to do:
```tsx
                   mask={(text) => {
                      const isNumber = !isNaN(parseInt(text?.slice(0, 1), 10));
                      const isParenthesis = text?.slice(0, 1) === '(';
                      if (isNumber || isParenthesis) {
                        return masks.phone;
                      } else {
                        return false;
                      }
                    }}
```

**Comment by CaioQuirinoMedeiros** [comment]
For now my suggestion is to return a mask that accepts any character:

```javascript
return [...Array.from(Array(100)).keys()].map(i => /./)
```

I'll consider implementing a way to return null or undefined in the function for this case.

**Comment by seyadeodin** [comment]
That worked perfectly. 
Obrigado Caio.
