### ISSUE TITLE
Keep the placeholder characters partially, while the user does not enter a value

### ISSUE THREAD

**Issue by williamjamir** [CaioQuirinoMedeiros/react-native-mask-input#4]
Hi

I'm using the CPF mask with a placeholder
```
___.____.___-__
```
But as soon as the user types the first digit, all characters from the placeholder are removed.
Is it possible to keep these characters while the user types the values? 
Something like this:

```
07_.____.___-__
  ^   (the cursor will be here, but the characters "_"  kept)
```

**Comment by CaioQuirinoMedeiros** [comment]
@williamjamir , unfortunately it's not possible, this is just a default value for the [TextInput placeholder](https://reactnative.dev/docs/textinput#placeholder).

...moreover, implementing such feature would be very complex and problematic, so it's not on my plans :/

**Comment by RodolfoSilva** [comment]
@CaioQuirinoMedeiros is it possible to hide the placeholder?
