### ISSUE TITLE
Email Mask doesn't work

### ISSUE THREAD

**Issue by TuvalZit18** [CaioQuirinoMedeiros/react-native-mask-input#42]
<MaskInput
      value={email}
      onChangeText={(masked, unmasked) => {
      console.log(masked);
      }}
      mask="/^(?=^.{1,80}$)([A-Za-z0-9._%-]+)@(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,})$/g"
    />
    
the error is this: undefined is not a function and it is pointing out to:

const maskHsObfuscation = React.useMemo( ()=>maskArray && !!maskArray.find(maskItem) => Array.isArray(maskItem)),[maskArray] );

**Comment by CaioQuirinoMedeiros** [comment]
You are using it completely wrong, please at least read the docs before opening a issue.

**Comment by TuvalZit18** [comment]
The docs said the mask field can get or an array or a string. I gave him string the represent regex for email (Btw, fixed the regex from the above message) and still get the same error.

in your docs: "An array where each item defines one character of the value. **If the item is a string, that string will be used, if it is an RegExp, it will validate the input on it**."

**Comment by CaioQuirinoMedeiros** [comment]
The mask should be an array, it's written clearly and you're misinterpreting it.
