### ISSUE TITLE
delete not working   when stand at the end of any part of the formated value i

### ISSUE THREAD

**Issue by khaled961** [CaioQuirinoMedeiros/react-native-mask-input#48]
i want when i stand at the end of any part of the formatted value when I delete last number from the previous part to be deleted 

https://github.com/CaioQuirinoMedeiros/react-native-mask-input/assets/54375389/32fce310-db09-440c-bf78-4c592ff785cf

**Comment by CaioQuirinoMedeiros** [comment]
You must be doing something wrong, prove it with reproducible code

**Comment by Mahmoud-SK** [comment]
> You must be doing something wrong, prove it with reproducible code

This has been happening to us for quite a long time also.

**Comment by CaioQuirinoMedeiros** [comment]
and yet I haven't seen a reproducible code 💁🏼‍♂️

**Comment by chizhkov422** [comment]
I also have the same issue.

https://github.com/CaioQuirinoMedeiros/react-native-mask-input/assets/40992073/9ee6636f-fd8d-4906-b2d7-bfc49214ae4d

` <TextInputMask
        value={value}
        onChangeText={(formatted, extracted) => {
          onChangeText(extracted || "");
        }}
        mask={["(", /\d/, /\d/, ")", " ", /\d/, /\d/, /\d/, " ", /\d/, /\d/, " ", /\d/, /\d/]}
       maxLength={14}
       placeholderTextColor="#BDBDBD"
      />`

**Comment by CaioQuirinoMedeiros** [comment]
See? your mask is completely wrong, read the fucking readme

**Comment by chizhkov422** [comment]
@CaioQuirinoMedeiros  This is a component with an example mask from the usage block in readme.

<img width="790" alt="image" src="https://github.com/CaioQuirinoMedeiros/react-native-mask-input/assets/40992073/0db09b56-4573-4dd2-8bc1-c94b0999109f">

The problem still here.

https://github.com/CaioQuirinoMedeiros/react-native-mask-input/assets/40992073/2723fbd1-c786-4baa-83c1-a1e809d7eee3

**Comment by MarkoCubicAgilno** [comment]
> [@CaioQuirinoMedeiros](https://github.com/CaioQuirinoMedeiros) This is a component with an example mask from the usage block in readme.
> 
> <img alt="image" width="790" src="https://private-user-images.githubusercontent.com/40992073/314440096-0db09b56-4573-4dd2-8bc1-c94b0999109f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA1OTI1NjYsIm5iZiI6MTc0MDU5MjI2NiwicGF0aCI6Ii80MDk5MjA3My8zMTQ0NDAwOTYtMGRiMDliNTYtNDU3My00ZGQyLThiYzEtYzk0YjA5OTkxMDlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjI2VDE3NTEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3OTBhNDhkMTQ1MmVjNWUwZDVjMGE3YzM3YzAzODBjZjM0MzQ0NmEzZmRjYWViZTlhOWNkZGRhM2ZiMWZmMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vRBaIXd8sSe8Ln5AuXEq9D2jgghFQkS_cLMgwWf9Pz0">
> The problem still here.
> 
>  Screen.Recording.2024-03-20.at.11.17.00.mov

I have the exact same issue, I am even using their `Masks.USA_PHONE`.
