### ISSUE TITLE
12hr Time format with AM/PM

### ISSUE THREAD

**Issue by Habeeb-007** [CaioQuirinoMedeiros/react-native-mask-input#49]
Hey i am new to react native i found this package when i search formatted textinput but dont know hot to format for this, could someone please help me to complete this format also i tried with custom format but the issue was i cant be ablto to set Am if the user press a and vice versa for pm and is it possible to change keyboard type as well while cursor in am part

**Comment by CaioQuirinoMedeiros** [comment]
`[/\d/, /\d/, ':', /\d/, /\d/, " ", /[AaPp]/, /[Mm]/]`
try this mask (I haven't test it though)

**Comment by Habeeb-007** [comment]
Thanks a lot bro its worked and i have added extra validation as well
