### ISSUE TITLE
Feature Request - Pass custom TextInput component

### ISSUE THREAD

**Issue by bombillazo** [CaioQuirinoMedeiros/react-native-mask-input#5]
Currently, this component relies on the base React Native TextInput component. 

It would be great to pass in a custom TextInput that this library could use to "wrap around" and maintain the functionality and styling of the passed component while adding the masking logic.

**Comment by nandorojo** [comment]
Yeah I want the same thing. @CaioQuirinoMedeiros would you accept a PR? I could do this in a few minutes.

**Comment by CaioQuirinoMedeiros** [comment]
Yes @nandorojo. But mind to keep it typescript friendly, I'm sure that this is the real challenge here

**Comment by nandorojo** [comment]
Could just use `customInputProps` which reads the generic of `InputComponent`'s props.

But I ended up just using `styled` from `dripsy` to achieve what I wanted anyway.

**Comment by CasuallyCaffeinated** [comment]
Any update on this?

**Comment by bombillazo** [comment]
Im no longer using RN, I'll let others request this if they need it.
